-- Drop tables in reverse order
DROP TABLE IF EXISTS articles CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS game_servers CASCADE;
DROP TABLE IF EXISTS network_tests CASCADE;
DROP TABLE IF EXISTS users CASCADE;
